### ISSUE TITLE
Run commands in ~/.duckdbrc on startup

### ISSUE THREAD

**Issue by pdpark** [tconbeer/harlequin#241]
Would be great if harlequin could read & execute the contents of `~/.duckdbrc` on startup. Mine looks something like this:
```
INSTALL httpfs;
LOAD httpfs;
SET s3_region='us-west-2';
```

**Comment by tconbeer** [comment]
Yes we are definitely doing this. Thanks for opening this issue!

**Comment by tconbeer** [comment]
@pdpark Do you think we should support dot commands? Or would just sql be ok? Many dot commands aren't relevant, but some, like .clone, might be nice? The others we could just ignore, so people could use the same file for the CLI and Harlequin. Would require some simple parsing on our end and translating dot commands into sql, since the Python API doesn't execute dot commands.
